apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api
  namespace: development
spec:
  selector:
    matchLabels:
      app: rest-api
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
      - name: rest-api
        image: docker.io/rizkyian78/test:0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8181
