kind: pipeline
type: docker

name: build

steps:
  - name: build
    image: docker
    commands:
      - docker build -t your-image-name .

  - name: publish
    image: plugins/docker
    settings:
      repo: your-registry/your-repo
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
