kind: pipeline
type: docker

name: my-pipeline

pipeline:
  - name: build
    image: docker
    commands:
      - docker build -t my-image-name .

  - name: test
    image: my-test-image
    commands:
      - run-tests.sh

  - name: deploy
    image: my-deploy-image
    commands:
      - deploy.sh
