apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-project
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/rizkyian78/template-rest-api
    targetRevision: HEAD
    path: ./
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true