apiVersion: v1
kind: Service
metadata:
  name: service-rest-api
  namespace: development
spec:
  selector:
    app: rest-api
  ports:
    - name: http
      protocol: TCP
      port: 8181
      targetPort: 8181