apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-role
  namespace: development
rules:
- apiGroups:
  - ""
  resources:
  - deployments
  - services
  - configmaps
  verbs:
  - create
  - get
  - update
  - delete
