apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: development
data:
  rabbitmq.conf: |
    loopback_users.guest = false
    listeners.tcp.default = 5672
    management.listener.port = 15672