name: Docker Image CI

on:
  push:
    tags:
      - '[0-9]+.*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIA2NRTVGVVQHVCJ3ND
        aws-secret-access-key: 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
        aws-region: us-east-1

    - name: Log in to Amazon ECR
      uses: docker/login-action@v1
      with:
        registry: 716294141291.dkr.ecr.us-east-1.amazonaws.com
        username: AWS
        password: yqyv0XUuTPiIRZvp+lmmbD8Mw5nW5Y/A2d360M0j

    # - name: push Docker image
    #   env:
    #    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    #    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    #    IMAGE_NAME: rizkyian78/test:${{ steps.tag.outputs.tagname }}
    #   run: |
    #       docker push $IMAGE_NAME
    #       echo "Tagged Latest Image $IMAGE_NAME"

    # - name: Log in to Amazon ECR
    #   uses: docker/login-action@v1
    #   with:
    #     registry: <YOUR_AWS_ACCOUNT_ID>.dkr.ecr.<YOUR_AWS_REGION>.amazonaws.com
    #     username: AWS
    #     password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # - name: Extract tag name
    #   id: tag
    #   run: echo ::set-output name=tagname::$(basename ${{ github.ref }})

    # - uses: actions/checkout@v3
    # - name: Build the Docker image
    #   run: |
    #     docker build . --file ./Dockerfile-gateway --tag rizkyian78/test:${{ steps.tag.outputs.tagname }}