name: Docker Image CI

on:
  push:
    tags:
      - '[0-9]+.*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      if: ${{ success() }}

    - name: Extract tag name
      id: tag
      run: echo ::set-output name=tagname::$(basename ${{ github.ref }})

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rizkyian78/test:${{ steps.tag.outputs.tagname }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
       push: true
       tags: rizkyian78/test:${{ steps.tag.outputs.tagname }}
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
