name: Docker Image CI

on:
  push:
    tags:
      - '[0-9]+.*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checking Connection to docker hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      if: ${{ success() }}

    - name: Extract tag name
      id: tag
      run: echo ::set-output name=tagname::$(basename ${{ github.ref }})

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rizkyian78/test:${{ steps.tag.outputs.tagname }}
    
    - name: push Docker image
      env:
       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
       IMAGE_NAME: rizkyian78/test${{ steps.tag.outputs.tagname }}
      run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push $IMAGE_NAME
