apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: development
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: http
    port: 15672
    targetPort: 15672